---
title: Naratree Capital
author: Naratree Capital
email: ''
description: We acquire small web businesses and SaaS products and help them grow
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
